# Generated by Django 5.1.1 on 2026-09-28 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_mediaasset_media_file_accesskey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_stream', models.DecimalField(decimal_places=4, default=0.01, max_digits=10)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streams_counted', models.PositiveIntegerField()),
                ('rate_applied', models.DecimalField(decimal_places=4, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_records', to=settings.AUTH_USER_MODEL)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_records', to='catalog.mediaasset')),
            ],
        ),
    ]
