# Generated by Django 5.1.1 on 2026-09-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royaltyrate',
            name='rate_per_stream',
            field=models.DecimalField(decimal_places=4, default=0.5, max_digits=10),
        ),
    ]
