# Generated by Django 5.1.1 on 2026-09-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingrecord',
            name='royalty_processed',
            field=models.BooleanField(default=False),
        ),
    ]
