# Generated by Django 5.1.1 on 2026-09-28 08:43

import django.core.files.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='media_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\dell\\OneDrive\\Desktop\\MediaMerge\\protected_media'), upload_to='media_files/'),
        ),
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to='catalog.mediaasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
