# Generated by Django 5.1.1 on 2026-09-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_mediaasset_media_file_accesskey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDatasetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500)),
                ('media_type', models.CharField(max_length=50)),
                ('release_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, db_index=True, max_length=100)),
                ('genre', models.CharField(blank=True, db_index=True, max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Movie Dataset Record',
                'verbose_name_plural': 'Movie Dataset Records',
            },
        ),
    ]
